name: mindweave
description: A new Flutter project.
version: 2.2.1+50
environment: 
  sdk: '>=2.19.1 <3.0.0'


dependencies: 
  flutter: 
    sdk: flutter

  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.1.0
  google_sign_in: ^6.0.2
  sign_in_with_apple: ^4.3.0


  get: ^4.6.5
  connectivity_plus: ^3.0.3
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.4
  outline_gradient_button: ^2.0.0+1
  intl: ^0.18.0
  permission_handler: ^10.2.0
  path_provider: ^2.0.13
  crypto: ^3.0.2

  #
  dio: ^5.0.3
  http: ^0.13.5
  fluttertoast: ^8.1.2
  purchases_flutter: ^4.9.0
  get_storage: ^2.0.3
  form_validator: ^2.1.1
  webview_flutter: ^4.0.6
  simple_gradient_text: ^1.2.4
  persistent_bottom_nav_bar: ^5.0.2
  font_awesome_flutter: ^10.4.0
  lottie: ^2.3.0
  carousel_slider: ^4.2.1
  toggle_switch: ^2.0.1
  animated_text_kit: ^4.2.2
  image_picker: ^0.8.7
  file_picker: ^5.2.6

  ##
  chat_gpt_sdk: ^2.0.6
  open_filex: ^4.3.2




dev_dependencies: 
  flutter_test: 
    sdk: flutter
  rename: ^2.0.1
  flutter_launcher_icons: ^0.12.0
  # flutter_native_splash: ^2.2.16
  flutter_lints: ^2.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon.png"
  min_sdk_android: 21 





flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/img/
    - assets/images/
    - assets/lottie/



  fonts: 
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratRomanBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
    - family: Raleway
      fonts: 
        - asset: assets/fonts/RalewayMedium.ttf
          weight: 500
    - family: Lato
      fonts: 
        - asset: assets/fonts/LatoExtraBold.ttf
          weight: 800
